// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe         = require("reason-react/src/reactDOMRe.js");
var ReasonReact        = require("reason-react/src/reasonReact.js");
var Page$ReactTemplate = require("./page.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Page$ReactTemplate.make("Hello!", /* array */[])), "index");

/*  Not a pure module */
